spring.application.name=backend
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

security.jwt.secret-key=${fine_secret_key}
security.jwt.access-token-expiration=6000000

file.upload-dir=uploads/images
app.frontend.url=https://fine-frontend.onrender.com

server.forward-headers-strategy=FRAMEWORK

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB